### ISSUE TITLE
PVE平手問題

### ISSUE THREAD

**Issue by 41047018s** [Raylin0722/SE-project#116]
| 項目 |  檢測PVE時間歸零平手時是否正常結束遊戲 |
| --- | --------|
| 前置條件 |1.進入PVE|
| 測試步驟 |1.時間耗盡<br>2.確認是否結束遊戲|
| 測試情形 |1.時間停止倒數<br>2.角色停止移動<br>3.跳出平手介面<br>4.技能按鈕無法使用<br>5.暫停裡的continue無法使用|
| 預期結果 | 1.Pass <br>2.Pass<br>3.Pass<br>4.Pass<br>5.Pass|
| 實際結果| 1.Pass <br>2.Pass<br>3.Fail : 不會跳出平手介面<br>4.Fail : 技能按鈕還是可以使用<br>5.Fail : 暫停裡的continue可以按 並且時間會變成倒數 2:00|

**Comment by heyimwei** [comment]
PVE平手後還可以按全體緩速技能
